ci_ntp_setup: yes
ci_ntp_server: ntp.zhdk.ch

ci_vim_mode: true

ci_ssh_keys:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/phiku')}}"

ci_removed_ssh_keys: []
