ci_executor_max_load: 3

ci_executor_trial_retention_duration: 1 Second
ci_executor_daily_reboot: yes

ansible_host: ci-executor.madek.zhdk.ch
ansible_user: root

executor_accepted_repositories:
- https://github.com/Madek/madek
- https://github.com/cider-ci/cider-ci
- https://github.com/SusanneSchumacher/demo.madek.zhdk.ch.git
- https://github.com/eins78/street.ars.is

ci_executor_trait_ansible: true
ci_executor_trait_git_crypt: true
ci_executor_trait_gpg: true
ci_executor_trait_leiningen: true
ci_executor_trait_nodejs: true
ci_executor_trait_ubuntu_desktop: false

# this is a vm
ci_ntp_setup: false
